# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SSKJ' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SSKJ

pod 'AFNetworking' # 网络请求
#    pod 'MBProgressHUD', "~> 0.8",:inhibit_warnings => true #提示框
#    pod 'JSONKit' #JSON解析、转换
    pod 'MJExtension',:inhibit_warnings => true  #数据字典转换模型
    pod 'MJRefresh',:inhibit_warnings => true #下拉和下拉刷新
    pod 'Masonry',:inhibit_warnings => true #页面布局
    pod 'SDWebImage' #网络图片 缓存
    pod 'IQKeyboardManager' #键盘
#    pod 'JWNetAutoCache',:inhibit_warnings => true #weibView 缓存
    pod 'RegexKitLite',:inhibit_warnings => true  #正则表达式
    pod 'Bugly'  #腾讯 BUG监控
    
    pod 'BANetManager',:inhibit_warnings => true #网络框架，封装get，post、put、delegate，文件上传下载，图片上传、视频上传
    #pod 'PopMenuView' #弹出视图
#    pod 'TYCyclePagerView',:inhibit_warnings => true #轮播视图
    #pod 'XLBasePageController' #多视图切换，处理视图生命周期
    #pod 'HXWeiBoPhotoPicker' #图片选择器
#    pod 'ACETelPrompt'  #拨打电话
    #pod 'fmdb' #本地数据库封装
#    pod 'RDVTabBarController',:inhibit_warnings => true  #自定义tabBar，包含选中、脚标，动画隐藏
#    pod 'TPKeyboardAvoiding',:inhibit_warnings => true  #解决键盘遮挡
#    pod 'YYCache',:inhibit_warnings => true

#    pod 'MMDrawerController',:inhibit_warnings => true #抽屉效果

    pod 'ReactiveObjC',:inhibit_warnings => true #RAC框架
    
    pod 'SDCycleScrollView',:inhibit_warnings => true #轮播图
    
    pod 'NinaPagerView'

end
